### ISSUE TITLE
Four stability tests fimeout instead of reporting success

### ISSUE THREAD

**Issue by gshimansky** [intel-go/nff-go#213]
When stability.json tests run, four tests out of ten don't report their status, run for one minute and get terminated on timeout. This makes them look as failed instead of passed.

**Comment by mbulatova** [comment]
It looks like testDoneEvent.Signal() should be removed from generatePacket(), it is excessive

**Comment by dkolistratova** [comment]
If we remove it, all tests will time out and it is an expected behavior, check stability.json config and set right ports. I guess it times out cause it waits on receive for some amount of packets, but never gets it because ports are wrong.

**Comment by dkolistratova** [comment]
I think it is not a bug, just wrong config provided.

**Comment by gshimansky** [comment]
Pull requests #215 and #216 fixed the problem and now tests successfully pass in default VM development environment.
