### ISSUE TITLE
Add High-Level Design document to the repo.

### ISSUE THREAD

**Issue by aregm** [intel-go/nff-go#235]
Add agreed with Chris and Anay HLD to reflect latest discussions.

**Comment by asunderr** [comment]
Done.
Refer https://github.com/intel-go/nff-go/blob/fixed_bng/Fixed-BNG-PGW_GO-NFF.pptx
https://github.com/intel-go/nff-go/wiki/Fixed-BNG-PGW-on-GO-over-NFF-Design-Construct-pseudo-code
