### ISSUE TITLE
Add Radius server support and test on  customer data

### ISSUE THREAD

**Issue by aregm** [intel-go/nff-go#238]

**Comment by gshimansky** [comment]
Initial implementation of caching lookup from RADIUS server committed to gregory/radius branch. It also has configuration for a single test user with two test attributes. Further implementation requires understanding how we keep user profile data on RADIUS server.

**Comment by aregm** [comment]
@asunderr Ashok waiting for your review.

**Comment by asunderr** [comment]
"... Further implementation requires understanding how we keep user profile data on RADIUS server..."
We need to converge on this with Chris Chase.. 
Or recommend a way based on your learnings/findings. 
Feel free to call me for any quick clarifications. 
Thanks

**Comment by aregm** [comment]
Wont' fix.
