### ISSUE TITLE
Prepare networking diagram and get approval from customer

### ISSUE THREAD

**Issue by aregm** [intel-go/nff-go#241]

**Comment by asunderr** [comment]
Refer: BNG OSS-BSS CP S11 SLA PGWU-NFF detailed network configuration w/ test infrastructure at:
[https://github.com/intel-go/nff-go/blob/fixed_bng/Fixed-BNG-PGW_GO-NFF.pptx](url)
[https://github.com/intel-go/nff-go/blob/fixed_bng/INTEL_NG40_Installation_HIO_RACK13_RAN16_NGIC5.xlsx](url)
