### ISSUE TITLE
Stable version 

### ISSUE THREAD

**Issue by marcusschiesser** [intel-go/nff-go#245]
Hi, for now we a referencing the latest commit of master. When can we expect a stable tag or release?

**Comment by marcusschiesser** [comment]
Sorry didn’t see https://github.com/intel-go/nff-go/releases/tag/v0.2 on my mobile client - is there a release plan?

**Comment by aregm** [comment]
Marcus, yes we have a release plan, which is mostly customer driven. We are moving to enrich the library with more traditional stuff, like LPM, QoS, ACL and moving to cloud-native with more scalability in both public and private clouds. If you are interested we can present where we are heading. What is your interest?

**Comment by alexblhr** [comment]
More examples would be nice :)

**Comment by aregm** [comment]
@alexblhr On their way. Anything particular you have in mind or need help with?

**Comment by marcusschiesser** [comment]
@aregm I would be mostly interested in the following:
1. support of DPDK 18 (looks like we need this to run nff-go on Azure)
2. more examples of how to optimize the performance of nff-go, particular we are having performance issues running on Openstack

**Comment by aregm** [comment]
@marcusschiesser 
> support of DPDK 18 (looks like we need this to run nff-go on Azure)
We had this in the backlog, moved to short-term task for the next release.

>more examples of how to optimize the performance of nff-go, particular we are having performance issues running on Openstack
Can you elaborate, what type of problems you are having?

**Comment by marcusschiesser** [comment]
@aregm thanks, we right now busy with other stuff, so we will probably wait for the next release to test DPDK 18. About the performance issues: It's hard to tell where the problem is, maybe some documentation about performance analysis would be helpful for the start.

**Comment by aregm** [comment]
@marcusschiesser I am closing this issue - feel free to open an issue with some more detailed description of performance issues.
