### ISSUE TITLE
Overhead of nff-go compared to using DPDK with C

### ISSUE THREAD

**Issue by devlo** [intel-go/nff-go#257]
Hi,

Calling C functions with CGO has high overhead, how nff-go get around it? 

Are there any benchmarks/measurements of similar high pps processing programs to see overhead of nff-go (CGO/Go) compared to using DPDK with C?

**Comment by aregm** [comment]
Hi, we are not calling DPDK for packet processing. Instead, we use DPDK as a fast I/O and call DPDK only for send/receive. When packets get to hugepages, we do not move them but manipulate through pointers directly from Go, bypassing DPDK. That is why we have comparable to C performance for packet processing per box. More information you can find in the article: https://dl.acm.org/ft_gateway.cfm?id=3166111&type=pdf.

**Comment by devlo** [comment]
Thanks @aregm I've read the paper now and as I assumed (as one of possible solutions) you are using pointers to ring buffers. I love the design of NFF and its scheduling of additional flow functions on free cores to meet the demand of higher traffic when buffers are highly populated with packets. Great work! Thanks for open sourcing this.

One more question, when traffic is low/machine is almost idle NFF-go will still eat one core for just polling the card (as you use dpdk polling drivers - so no interrupts), right?
