### ISSUE TITLE
Missing cleanup of rte_eal_cleanup from DPDK 18.02

### ISSUE THREAD

**Issue by guesslin** [intel-go/nff-go#263]
Hi, we are using nff-go and want to re-init it during process executing, but always got errors like

```
Apr 10 03:29:52 ubuntu router[951]: ------------***-------- Initializing DPDK --------***------------
Apr 10 03:29:52 ubuntu router[951]: EAL: FATAL: already called initialization.
Apr 10 03:29:52 ubuntu router[951]: EAL: already called initialization.
Apr 10 03:29:52 ubuntu router[954]: EAL: Error - exiting with code: 1
Apr 10 03:29:52 ubuntu router[951]:   Cause: Error with EAL initialization
Apr 10 03:29:52 ubuntu router[954]: Error with EAL initialization
```

I checked [DPDK 18.02 Release](https://dpdk.org/doc/guides/rel_notes/release_18_02.html), they have a new function `rte_eal_cleanup` to cleanup resource of DPDK used.
Is there any reason nff-go not calling `rte_eal_cleanup`?

**Comment by ifilippov** [comment]
The problem here is deeper than DPDK cleanup: now NFF-GO doesn't stop goroutines before exit. So if you re-init it you will have old handles still working plus new ones. We have this issue in our TODO list, however with less priority. 

Can you please point if you need this feature - we will implement it for future releases?

**Comment by aregm** [comment]
We should do this after #256 is merged. @guesslin you can use 'develop' branch to have this feature soon.

**Comment by guesslin** [comment]
@ifilippov Yes, the Scheduler stopping is another problem for the re-init issue. We need this feature for runtime re-init our process from an update status.

**Comment by ifilippov** [comment]
@guesslin I've done stopping in two functions, please refer to https://github.com/intel-go/nff-go/commit/b4c19bc3a4766658df30794edb2ce71031086135. However it appears that DPDK cleanup doesn't cleanup everything for initial state. So you won't be able to re-init. Here is an answer from DPDK guys:

"That function was added as it was required to release hugepage memory from secondary processes when shutting down. In the long term, it is intended to provide a "clean" shutdown of all of DPDK resources, however it is not that today. In current code, rte_eal_init() can still only be called once per process."

Now you can stop our framework by SystemStop and call SystemStart with new graph configuration without re-init DPDK. Please, refer to develop branch for this.

**Comment by guesslin** [comment]
@ifilippov Thanks, I'll test with develop branch.

**Comment by sitilge** [comment]
@guesslin , @ifilippov have you managed to get it working? I'm encountering the same issues.
