### ISSUE TITLE
Latency performance test

### ISSUE THREAD

**Issue by ifilippov** [intel-go/nff-go#291]
What is speed parameter? Can you please make this test more actual.

**Comment by ifilippov** [comment]
Also you should change this test to generate some files (with modified perf_compare) which can be compared with previous ones.

**Comment by mbulatova** [comment]
Current test is in my branch https://github.com/intel-go/nff-go/tree/mbulatova/latency
Added scope according to perf.json (perf_main, perf_light, perf_seq)
Takes 34m to complete

**Comment by mbulatova** [comment]
After #353 is implemented, writing to files will not be necessary
