### ISSUE TITLE
We should have normal way to build in DEBUG mode

### ISSUE THREAD

**Issue by ifilippov** [intel-go/nff-go#319]
This should include:
building DPDK in debug
switch on DEBUG mode inside low.h
the following magic:
    Use the following line to build Go files without optimizations
    go build -gcflags '-N -l' $< $(COMMON_FILES)

**Comment by dkolistratova** [comment]
fixed

**Comment by ifilippov** [comment]
Your patch is incomplete.

1) dpdk/Makefile:
# Uncomment to build DEBUG DPDK
# export EXTRA_CFLAGS=-mno-fsgsbase -mno-f16c -g -O0
what is these? Do you check that you build DPDK in debug mode? Remove this lines or use them

2) Addition: +export CFLAGS = -g -O0 -I$(RTE_SDK)/$(RTE_TARGET)/include -std=gnu11 -m64 -pthread -march=native -mno-fsgsbase -mno-f16c -include rte_config.h
is duplicated with above line. "export CFLAGS = -g -O0" is enough because other flags are set earlier without conditions.

3) We have DEBUG define in low.h - what should we do with it? I would like to automate it also as pointed in initial issue. Debug mode should switch low.h on. Also we should have some mode to switch only it, without golang and DPDK debugging.

4) About Readme - a) - please, fix indents, b) - you shouldn't recommend use only "-j8":
two variants: make NFF_GO_DEBUG=y or make debug are quite enough.

**Comment by dkolistratova** [comment]
1: ok
2: they are not duplicated, not +=, but = is used. It was commented in this way
3: ok
4: -j8 was used above in "Building NFF-GO"  and I just made it consistent with this line

**Comment by ifilippov** [comment]
Done.
