### ISSUE TITLE
Checksum test fails with gotest with Cause: rte_eal_init can't parse all parameters

### ISSUE THREAD

**Issue by dkolistratova** [intel-go/nff-go#322]
reproducer:

```
cd test/stability/testCksum
make testing
```
Appeared after rebasing on develop branch today, worked last week (last commit 2aa828fc1d111eb7dedc9fdb1d30992643c73221 - merge pull request 306)

**Comment by ifilippov** [comment]
How can you explain what happens between last week and now? Please not merge before this explanation.

**Comment by dkolistratova** [comment]
fixed, close

**Comment by mbulatova** [comment]
Was caused by 4b3d81cae865e348ecf496b31d7af380c3946461

**Comment by ifilippov** [comment]
Please, point here exact reason.

**Comment by mbulatova** [comment]
This initialization dpdkLogLevel = "--log-level=0" was removed by mistake in 4b3d81c
