### ISSUE TITLE
testCksum fails with flags "-udp -tcp -ipv4 -ipv6"

### ISSUE THREAD

**Issue by dkolistratova** [intel-go/nff-go#323]
git bisect bad
8df5cdbeacd90f7d315d6ec7e12697eb0d90b61b is the first bad commit

reproducer:
```
 ./test/stability/testCksum/testCksum -udp -tcp -ipv4 -ipv6 -number 10000
```

fails with 
```
TEST FAILED
Bad data found in the packet: fdfe8aa4586acfce
```

**Comment by ifilippov** [comment]
As Daria pointed these command line invocate random tests. Daria should provide exact line without random generations.

**Comment by dkolistratova** [comment]
fixed
