### ISSUE TITLE
Merge test fails, ratio of received packets got low

### ISSUE THREAD

**Issue by dkolistratova** [intel-go/nff-go#329]
Degradation starts from commit:
77230e0cefb6d9413d8b175e0dd96749d5a32264 is the first bad commit
commit 77230e0cefb6d9413d8b175e0dd96749d5a32264
Author: Ilia Filippov <ilia.filippov@intel.com>
Date:   Tue Mar 20 12:36:22 2018 -0600

    Combined clonable flow functions to one "Line" flow function

    Changes short:
    1) Sequential segments of functions handle, split, separate and partition are now
    - invocated at one core
    - clonned simultaneously
    - don't use any rings and mbuf inside them
    2) Vector functions use mask instead of packets regrouping
    3) Partition is now clonnable function

    Changes long:
    Flow graph is now divided into four parts.
    1) "Get" functions: Receive, Receive from KNI, Receive from File, Generate, Fast generate
    2) "Copy" function: Copy
    3) "Segment" functions: Handle, Separate, Split, Partition
    4) "Set" functions: Send, Send to KNI, Send to file, Stop
    1 - is always the first.
    2 - can be after 1 or 3
    3 - can be after 1 or 2
    4 - can be after 1, 2 or any function from 3 group
    Merge function interrupts segment and can be placed wherever user wants
    Changes from scalar to vector code also interrupts segment

**Comment by ifilippov** [comment]
Can't reproduce. Can you please point exact reproducer.

**Comment by ifilippov** [comment]
This commit is first "new" merge commit. It increase latency a little bit. I fix all tests except Merge, Merge should be fixed during https://github.com/intel-go/nff-go/issues/286.

Also Merge should pass after recent speed changes.

**Comment by dkolistratova** [comment]
Does not fail now, close
