### ISSUE TITLE
Test Checksum fails with panic: runtime error: index out of range

### ISSUE THREAD

**Issue by dkolistratova** [intel-go/nff-go#331]
panic: runtime error: index out of range

goroutine 19 [running, locked to thread]:
math/rand.(*rngSource).Uint64(...)
        /opt/go1.9.linux-amd64/src/math/rand/rng.go:246
math/rand.(*rngSource).Int63(0xc4200ff500, 0x6650e2484d54eb45)
        /opt/go1.9.linux-amd64/src/math/rand/rng.go:231 +0x8a
math/rand.(*Rand).Int63(0xc4200e2630, 0x6650e2484d54eb45)
        /opt/go1.9.linux-amd64/src/math/rand/rand.go:82 +0x33
math/rand.(*Rand).Int(0xc4200e2630, 0x6650e2484d54eb45)
        /opt/go1.9.linux-amd64/src/math/rand/rand.go:100 +0x2b
github.com/intel-go/nff-go/test/stability/testCksum.initPacketCommon(0x7eff7eeeb400, 0x4e2)
        /localdisk/newProj/src/github.com/intel-go/nff-go/test/stability/testCksum/testCksum.go:416 +0x86
github.com/intel-go/nff-go/test/stability/testCksum.generateIPv4UDP(0x7eff7eeeb400)
        /localdisk/newProj/src/github.com/intel-go/nff-go/test/stability/testCksum/testCksum.go:464 +0x5d
github.com/intel-go/nff-go/test/stability/testCksum.generatePacket(0x7eff7eeeb400, 0x0, 0x0)
        /localdisk/newProj/src/github.com/intel-go/nff-go/test/stability/testCksum/testCksum.go:379 +0x148
github.com/intel-go/nff-go/flow.pFastGenerate(0x702c20, 0xc4200e2660, 0xc42013e000, 0xc42013e060, 0xc420120000, 0xc4200ac5a0, 0x1, 0x1)
        /localdisk/newProj/src/github.com/intel-go/nff-go/flow/flow.go:1088 +0x3b1
github.com/intel-go/nff-go/flow.(*scheduler).startFF.func1(0xc420122000, 0x1)
        /localdisk/newProj/src/github.com/intel-go/nff-go/flow/scheduler.go:217 +0x24c
created by github.com/intel-go/nff-go/flow.(*scheduler).startFF
        /localdisk/newProj/src/github.com/intel-go/nff-go/flow/scheduler.go:211 +0x253
exit status 2
FAIL    github.com/intel-go/nff-go/test/stability/testCksum     4.924s
make: *** [Makefile:10: testing] Error 1

**Comment by dkolistratova** [comment]
When I change fast generator to simple generator, problem disappears!

**Comment by dkolistratova** [comment]
minimal reproducer:

```
go
package main

import (
	"math/rand"
	"github.com/intel-go/nff-go/flow"
	"github.com/intel-go/nff-go/packet"
)

var (
	rnd    *rand.Rand
)

func main() {
	rnd = rand.New(rand.NewSource(13))	
	config := flow.Config{
		DPDKArgs: []string{"--log-level=0"},
	}
	flow.CheckFatal(flow.SystemInit(&config))
	flow1, err := flow.SetFastGenerator(generatePacket, uint64(1000000), nil)
	flow.CheckFatal(err)
	flow.CheckFatal(flow.SetStopper(flow1))
	flow.CheckFatal(flow.SystemStart())
}


func generatePacket(emptyPacket *packet.Packet, context flow.UserContext) {
	length := uint16(1384)
	packet.InitEmptyIPv4UDPPacket(emptyPacket, uint(length))
	data := (*[1 << 30]byte)(emptyPacket.Data)[0:length]
	for i := range data {
		data[i] = byte(rnd.Int())
	}
}
```

**Comment by ifilippov** [comment]
Rand with NewSource is not thread safe as mention in documentation. If function was clonned - so the reason is clear and you can use NewSource inside context cloning for this.

**Comment by dkolistratova** [comment]
Yes:
DEBUG: Start SCHEDULER at 0 core
DEBUG: Start STOP at scheduler 0 core
DEBUG: Start new FlowFunction or clone for fast generator at 1 core
DEBUG: Start new FlowFunction or clone for sender at 2 core
DEBUG: Start new FlowFunction or clone for receiver at 3 core
DEBUG: Start new FlowFunction or clone for segment at 4 core
------------***--------- NFF-GO-GO Started --------***------------
DEBUG: Start new FlowFunction or clone for fast generator at 5 core
panic: runtime error: index out of range

So, a bug in cksum test, I'll fix

**Comment by dkolistratova** [comment]
fixed
