### ISSUE TITLE
report_compare doesn't work

### ISSUE THREAD

**Issue by ifilippov** [intel-go/nff-go#393]
You can go to my directory at nbdw21 and found test/framework/main:
old
new_2
new_3
directories with real performance measurements and report.json files. I have a report_compare output:
packets: +Inf, megabits: +Inf, cores: 8.660099
You can check that there are no zeros in files by using
old_compare, new_2_compare, new_3_compare files which are generated with perf_compare tool.

**Comment by gshimansky** [comment]
The reason is simple. Doubles are just overflowed with packets and megabits because there are too many tests there and values multiplication produces number too big to hold in float64.

**Comment by gshimansky** [comment]
New approach is to calculate geomean using a sum of logarithms instead of multiplying all values. RP #394.
