### ISSUE TITLE
Negative generator speed

### ISSUE THREAD

**Issue by dkolistratova** [intel-go/nff-go#412]
when speed is set to 10000000000000000000, we get the following:

DEBUG: Mempool usage slow operations 0 from 8191
DEBUG: ---------------
DEBUG: Start new clone for fast generator instance 0 at 13 core
DEBUG: System is using 14 cores now. 74 cores are left available.
DEBUG: Current speed of fast generator is 6400 PKT/S, target speed is -9223372036854775808 PKT/S
DEBUG: Mempool usage fast generate 864 from 8191
DEBUG: Mempool usage slow operations 0 from 8191
DEBUG: ---------------
DEBUG: Start new clone for fast generator instance 0 at 14 core
DEBUG: System is using 15 cores now. 73 cores are left available.
DEBUG: Current speed of fast generator is 5952 PKT/S, target speed is -9223372036854775808 PKT/S
DEBUG: Mempool usage fast generate 896 from 8191
DEBUG: Mempool usage slow operations 0 from 8191
DEBUG: ---------------
DEBUG: Start new clone for fast generator instance 0 at 15 core
DEBUG: Start new clone for fast generator instance 0 at 16 core
DEBUG: System is using 17 cores now. 71 cores are left available.
DEBUG: Current speed of fast generator is 4480 PKT/S, target speed is -9223372036854775808 PKT/S
DEBUG: Mempool usage fast generate 960 from 8191
DEBUG: Mempool usage slow operations 0 from 8191
DEBUG: ---------------
DEBUG: Start new clone for fast generator instance 0 at 17 core
DEBUG: System is using 18 cores now. 70 cores are left available.

Not critical, but looks peculiar.

**Comment by ifilippov** [comment]
Done.
