### ISSUE TITLE
Panics in our pktgen (performance problems)

### ISSUE THREAD

**Issue by ifilippov** [intel-go/nff-go#430]
Remove meaningless error checks in our pktgen:
fillIPHdr fillICMPHdr etc can't return error (from current code). So remove checkings after them
fillEtherHdr can return error only with VLANs - call panic inside VLAN branch, do not check this for all other packets
Look through all other functions for such checks.

Try to remove some meaningful error checking (without pull request). Compare before/after performance.

**Comment by ifilippov** [comment]
This
panic(fmt.Sprintf("fillPacketl3 failed, unknovn version %d", l3.Version))
Should be checked while you are building table, not at critical path.

**Comment by dkolistratova** [comment]
@ifilippov, by "Should be checked while you are building table, not at critical path." you suggest to create generateIP4, generateIP6 instead of one?

**Comment by dkolistratova** [comment]
~4% faster, it could be measurement error

**Comment by dkolistratova** [comment]
done
