### ISSUE TITLE
Interfaces in our pktgen (performance problems)

### ISSUE THREAD

**Issue by ifilippov** [intel-go/nff-go#431]
Try to get rid of interface resolving during packet generation. Rewrite this via unsafe pointers or complete (redundant) set of pointers for all supporting protocols. Compare before/after performance (without pull request firstly).

**Comment by ifilippov** [comment]
You should use not genParameters as a context but *genParameters. Besides decreasing size of parameter this will allow to make type assertion only one time. You can look at ipsec.go how to do this.

**Comment by dkolistratova** [comment]
I use  &context which actually is *genParameters.

**Comment by dkolistratova** [comment]
done
