### ISSUE TITLE
Memory allocation in our pktgen (performance problems)

### ISSUE THREAD

**Issue by ifilippov** [intel-go/nff-go#432]
You have enormous number of redundant memory allocations, e.g. for fillEtherHdr function (is used for all packets) you have:
~4 slice making and ~6 slice copying for reach packet. It is too much for performance.
There are two variants:
1) "Right one": you should pass pointer to already allocated packet space to all functions and they will fill in this packet's addresses etc.
2) "Worse one": if it is too complex and you need to copy addresses etc. to packet at the final stage you should at least pre-allocate slices for preparing these addresses before critical path.

**Comment by dkolistratova** [comment]
Some address crops and maybe do something with Bytes() call (uses make inside)

**Comment by ifilippov** [comment]
Need to investigate further.

**Comment by ifilippov** [comment]
Will not fix. We need to reinvent pktgen based on this.

**Comment by ifilippov** [comment]
I was wrong. NffPktgen is very smart and has multiple great abilities. We shouldn't reinvent something new. We should dramatically increase current performance instead. Current roadmap is:

1) Remove slices in MAC and IPv4 addresses - they should be uint64. This will remove lots of copies and byte comparisons.
2) Fix context copying. Currently it doesn't have "deep" copy and all clones use the same variables under cloned pointers - even two clones slow down.
3) Overall structure should be changed: we should divide functionality for four parts: high performance generating tasks / other generating tasks (IPv6) / config parsing / utilities (APIs).
4) Then we should do something with straight data copying. Usage of vector randoms or predefined random sets look quite reasonable.

**Comment by ifilippov** [comment]
After https://github.com/intel-go/nff-go/commit/56b26dfd183d6f81cafbf5cbc6d963d28e58b029 and https://github.com/intel-go/nff-go/commit/d403142758958a31a9dd84e5e660c64abe7ae2aa commits nffPktgen works better (memory allocation and cloning problems have gone). IPv4 with data copying is approximately 5GB/s per core.

We can do better in performance if we allocate some data in mempool in advance or use vector random functions.

Also we can do better in stability by changing iterations counters while cloning, (for example ipv4_address+=2 for two clones).

We will continue nffPktgen improvements after user requests. Feel free to reopen this issue or submit a new one if you would like any new features.
