### ISSUE TITLE
No packet received after upgrade to 0.4.1 

### ISSUE THREAD

**Issue by mkfsn** [intel-go/nff-go#438]
Hi, I just upgrade my project from nff-go 0.3 to 0.4.1 but suddenly no packet was received.

Do you have any idea what happens there? I change nothing in my code - just use the different tag of nff-go.

Or do you have any suggestion how do I find out the reason?

This is part of my code:

```go
func init() error {
	config := &flow.Config{
		HWTXChecksum: true,
	}
	flow.SystemInit(config)
	
	port := getEthPort(n.nicInfo.HWAddress)
	mainFlow, err := flow.SetReceiver(port)
	if err != nil {
		return err
	}
	
        // set handler
	if err := flow.SetHandlerDrop(mainFlow, handler, nil); err != nil {
		return err
	}
	
	if err := flow.SetSender(mainFlow, port); err != nil {
		return err
	}

	go func() {
		if err := flow.SystemStart(); err != nil {
			logger.Println("Couldn't start NFF system:", err.Error())
		}
	}()

	return nil
}

func handler(pkt *packetlib.Packet, _ flow.UserContext) bool {
	nffpacket := newNFFPacket(pkt)
	// incomming := make(chan NFFPacket)
        incomming <- nffpacket
	return <-nffpacket.verdict
}
```

**Comment by gshimansky** [comment]
Hello. I see no problems in your code. Maybe there is a difference between DPDK versions? After switching to new version of NFF-Go and therefore switching included DPDK versions, did you insert new version of kernel module and rebind your ports?

**Comment by mkfsn** [comment]
Hi @gshimansky, I tested both 0.3 and 0.4.1 with the same DPDK version (18.02) and also the same kernel version.

**Comment by mkfsn** [comment]
Sorry for the late reply.

I tested 0.3 and 0.4.1 on AWS, and right now I have some problems with accessing the VM so I can't provide the details for now (but I'll provide it as soon as possible)

@aregm Yes, the only change is the NFF-Go version.

**Comment by mkfsn** [comment]
Hi, here's some details:

* CPU: Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
* Ethernet driver: ENA, version: 1.5.0K
* Kernel: 4.4.0-1063
* Linux Distribution:  Ubuntu 16.04.5 LTS
* go version: 1.10

**Comment by mkfsn** [comment]
Hi, I tried to find out the problem by checking out to some commits, and then found that:

+  works: 1d85136cbb76ab63d118383239efd0f7bde4eca1 (PR #384)
+  not working: 09f7b3e98ce100a96eb541eecee4d12bae9cda6a (PR #385)

**Comment by gshimansky** [comment]
Do you mean that commit 09f7b3e is the first one which doesn't work for you? It looks quite harmless to me. You can try this patch to check if you really don't receive any packets:
```
diff --git a/low/low.h b/low/low.h
index 9df0fd5..50b751d 100644
--- a/low/low.h
+++ b/low/low.h
@@ -328,6 +328,7 @@ void receiveRSS(uint16_t port, volatile int32_t *inIndex, struct rte_ring **out_
                for (int q = 0; q < inIndex[0]; q++) {
                        // Get packets from port
                        uint16_t rx_pkts_number = rte_eth_rx_burst(port, inIndex[q+1], bufs, BURST_SIZE);
+            printf("Received %d packets\n", rx_pkts_number);
                        if (unlikely(rx_pkts_number == 0)) {
                                continue;
                        }
```

**Comment by mkfsn** [comment]
@gshimansky Thank you. Yes, that's what I mean.

I tried the patch you provided based on tag 0.4.1, and seeing always `Received 0 packets`.

Do you have any suggestion?

**Comment by mkfsn** [comment]
I actually check the receive packet number in DPDK debug log:

```
Aug 29 02:31:46 ip-10-1-254-146 router[25245]: DEBUG: ---------------
Aug 29 02:31:47 ip-10-1-254-146 router[25245]: DEBUG: System is using 4 cores now. 0 cores are left available.
Aug 29 02:31:47 ip-10-1-254-146 router[25245]: DEBUG: Current speed of segment is 0 PKT/S, queue length is 0 packets
Aug 29 02:31:47 ip-10-1-254-146 router[25245]: DEBUG: Mempool usage receive 1016 from 32764
Aug 29 02:31:47 ip-10-1-254-146 router[25245]: DEBUG: Mempool usage slow operations 0 from 32764
Aug 29 02:31:47 ip-10-1-254-146 router[25245]: DEBUG: ---------------
```

The "Current speed of segment" is always 0 PKT/S when I use this https://github.com/intel-go/nff-go/commit/09f7b3e98ce100a96eb541eecee4d12bae9cda6a commit, and I'll see some numbers when I use this https://github.com/intel-go/nff-go/commit/1d85136cbb76ab63d118383239efd0f7bde4eca1 commit

**Comment by mkfsn** [comment]
Hi, I think I found the overflow bug, and I've created a PR for this (#468).

Also, I've tested that solved my problem (no packet received) when using nff-go 0.4

**Comment by mkfsn** [comment]
Hi, due to the overflow bug, `0.4` and `0.4.1` is not working for me, but I don't want to use `0.3` as I need the `SystemStop`.

Do you have any suggestion or how's the progress of the next release (tag)?

BTW, I guess this issue could be closed.

**Comment by gshimansky** [comment]
Did you check version 0.6.1 which was released in October?

**Comment by guesslin** [comment]
@gshimansky we tried 0.6.1, and we can receive packets, but have problem on sending packet out, still digging for a reason.

**Comment by gshimansky** [comment]
Perfect! I suppose it is time we can close this issue.
