### ISSUE TITLE
SystemStop should cause SystemStart to return

### ISSUE THREAD

**Issue by blitzrk** [intel-go/nff-go#503]
In order for my application to handle shutdown signals and perform certain cleanup after my flow stops, I need to be able to gracefully stop the DPDK flow and get notified of this. Ideally `SystemStart` would take a `context.Context` and return an error after gracefully shutting down once the context was cancelled. However, it would also be sufficient if calling `SystemStop` caused `SystemStart` to return _or_ if `SystemStop` was known to only return once the flow was stopped (the latter wouldn't be idiomatic). However, this does not seem to work.

Is `flow.SystemStop` intentionally broken? It seems that `const wasStopped = 9` was chosen such that https://github.com/intel-go/nff-go/blob/v0.7.0/flow/scheduler.go#L573 would set the stopFlag to `3` (an unknown state) and that would therefore keep `SystemStop` running in an infinite loop here: https://github.com/intel-go/nff-go/blob/v0.7.0/flow/scheduler.go#L327

**Comment by blitzrk** [comment]
My system was reproducibly hanging upon calling `SystemReset`, but upon testing on a different machine, it worked. Perhaps there's an unrelated bug in DPDK, because my application runs fine on an Atom (silvermont) box, but completely hangs the kernel (not the process) on a Broadwell box.

So this issue can definitely be closed. Sorry about that. It would be good to change the documentation on SystemStart to indicate that it does not "not return," but in fact just blocks until SystemStop is called.

By "DPDK flow" and "flow stopped" I was just referring to the processing going on between SystemStart and SystemStop since they're in the flow library.

**Comment by aregm** [comment]
@blitzrk, Ben, can you please send more info about the configuration that fails and steps to reproduce?

**Comment by ifilippov** [comment]
Generally you shouldn't use SystemReset, because it includes deprecated DPDK functionality:

// SystemReset stops whole framework plus cleanup DPDK
// TODO DPDK cleanup is now incomplete at DPDK side
// It is n't able to re-init after it and also is
// under deprecated pragma. Need to fix after DPDK changes.

If you are sure that it hangs inside SystemStop - than we will try to fix it. If it hangs after SystemStop inside DPDK cleanup - it is big chance that it is due to DPDK functionality, we can't influence it.

**Comment by blitzrk** [comment]
Not sure if you want me to separate this out into another issue, but here we go:

Here are my devices:

```
(~)$ dpdk-devbind --status-dev net

Network devices using DPDK-compatible driver
============================================
<none>

Network devices using kernel driver
===================================
0000:08:00.0 'I350 Gigabit Network Connection 1521' if=eth0 drv=igb unused=igb_uio,uio_pci_generic *Active*
0000:08:00.1 'I350 Gigabit Network Connection 1521' if=eth1 drv=igb unused=igb_uio,uio_pci_generic
0000:0b:00.0 'I350 Gigabit Network Connection 1521' if=eth2 drv=igb unused=igb_uio,uio_pci_generic *Active*
0000:0b:00.1 'I350 Gigabit Network Connection 1521' if=eth3 drv=igb unused=igb_uio,uio_pci_generic
0000:0b:00.2 'I350 Gigabit Network Connection 1521' if=eth4 drv=igb unused=igb_uio,uio_pci_generic
0000:0b:00.3 'I350 Gigabit Network Connection 1521' if=eth5 drv=igb unused=igb_uio,uio_pci_generic

Other Network devices
=====================
<none>
```

Here's a test DPDK app I'm using to bind a driver, run until Ctrl+C, then rebind the original driver:

```
package main

import (
        "context"
        "flag"
        "log"
        "os"
        "os/signal"
        "syscall"

        "github.com/intel-go/nff-go/devices"
        "github.com/intel-go/nff-go/flow"
)

var (
        pciBusAddr = flag.String("pci", "", "PCI bus address of eth controller")
        driver     = flag.String("drv", devices.DriverUioPciGeneric, "Device driver to use")
)

func main() {
        ctx, cancel := context.WithCancel(context.Background())
        defer cancel()

        // Parse flags
        flag.Parse()
        if *pciBusAddr == "" {
                log.Fatal("-pci flag required")
        }
        switch *driver {
        case devices.DriverIgbUio,
                devices.DriverVfioPci,
                devices.DriverUioPciGeneric:
        default:
                log.Fatalf("unknown driver: %s", *driver)
        }

        // Bind device to DPDK driver
        ethDev, err := devices.GetPciDeviceByPciID(*pciBusAddr)
        if err != nil {
                log.Fatalf("error reading NIC device: %v", err)
        }
        prevDriver, err := ethDev.CurrentDriver()
        if err != nil {
                log.Fatalf("error getting current net driver: %v", err)
        }
        if err := ethDev.Bind(*driver); err != nil {
                log.Fatalf("error binding device to net driver: %v", err)
        }

        // Handle interrupts
        intC := make(chan os.Signal, 3)
        defer close(intC)
        go func() {
                <-intC
                cancel()
                log.Print("Gracefully shutting down. Interrupt 2x to force quit.")
                <-intC
                log.Print("Interrupt 1 more time to force quit")
                <-intC
                os.Exit(1)
        }()
        signal.Notify(intC, syscall.SIGINT, syscall.SIGTERM)

        // Init DPDK
        if err := flow.SystemInit(nil); err != nil {
                log.Fatalf("error initializing DPDK: %v", err)
        }

        // Setup packet flow graph
        inputFlow, err := flow.SetReceiver(0)
        if err != nil {
                log.Fatalf("error creating incoming packet source: %v", err)
        }
        if err := flow.SetStopper(inputFlow); err != nil {
                log.Fatalf("error creating flow stopper: %v", err)
        }

        // Shutdown upon context cancellation
        done := make(chan struct{})
        go func() {
                defer close(done)
                <-ctx.Done()
                flow.SystemReset()
        }()

        // Start app
        if err := flow.SystemStart(); err != nil {
                log.Fatalf("dpdk app exited with an error: %v", err)
        }

        // Wait for cleanup to complete
        <-done

        // Rebind to original driver
        if err := ethDev.Bind(prevDriver); err != nil {
                log.Fatalf("error rebinding driver: %v", err)
        }
}
```

I can run it successfully with `uio_pci_generic`:

```
(~)$ sudo ./broken-drivers -pci 0000:08:00.1
------------***-------- Initializing DPDK --------***------------
EAL: Detected 16 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:08:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:08:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:0b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:0b:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:0b:00.2 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:0b:00.3 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
------------***------ Initializing scheduler -----***------------
DEBUG: Scheduler can use cores: [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15]
------------***---------- Creating ports ---------***------------
DEBUG: Port 0 MAC address: 14:02:ec:49:42:fd
------------***------ Starting FlowFunctions -----***------------
DEBUG: Start SCHEDULER at 0 core
DEBUG: Start STOP at scheduler 0 core
DEBUG: Start new instance for receiver
DEBUG: Start new clone for receiver instance 0 at 1 core
------------***---------- NFF-GO Started ---------***------------
DEBUG: ---------------
DEBUG: System is using 2 cores now. 14 cores are left available.
DEBUG: ---------------
DEBUG: System is using 2 cores now. 14 cores are left available.
DEBUG: ---------------
DEBUG: System is using 2 cores now. 14 cores are left available.
^CGracefully shutting down. Interrupt 2x to force quit.
DEBUG: Stop instance for receiver
DEBUG: Stop clone
```

When I run it with `sudo ./broken-drivers -pci 0000:08:00.1 -drv igb_uio` the output is the same - meaning it gets past cleanup - but it hangs the kernel and I need to physically reboot the machine.

For some reason when I run it with `strace`, after I physically reboot the machine, the trace file is empty, but I have found that altering the program to simply unbind at the end after cleanup doesn't crash the machine, _only binding back to igb_. This seems eminently important and probably tells us all that strace would: that the last thing to happen is writing to the `igb` bind file in sysfs.

In the past I've also seen my kernel hang when trying to unbind `vfio-pci`, but now I'm also seeing it (here) after unbinding `igb_uio` and then binding `igb`, but I have no idea why the combination matters.

**Comment by blitzrk** [comment]
> Generally you shouldn't use SystemReset, because it includes deprecated DPDK functionality:
> 
> // SystemReset stops whole framework plus cleanup DPDK
> // TODO DPDK cleanup is now incomplete at DPDK side
> // It is n't able to re-init after it and also is
> // under deprecated pragma. Need to fix after DPDK changes.
> 
> If you are sure that it hangs inside SystemStop - than we will try to fix it. If it hangs after SystemStop inside DPDK cleanup - it is big chance that it is due to DPDK functionality, we can't influence it.

The issue is definitely outside of SystemStop, so I'll close this ticket. As I was saying before, it would be good to change the documentation on SystemStart to indicate that it does not "not return," but in fact just blocks until SystemStop is called.
