### ISSUE TITLE
Flow package should not call os.Exit

### ISSUE THREAD

**Issue by blitzrk** [intel-go/nff-go#504]
Throughout the `flow` package, including in `SystemInit` and `SystemStart`, there are calls to `common.LogFatal`, which in turn calls `os.Exit(1)`. This makes it impossible to create a DPDK application that has any sort of cleanup. For example, wrapped around my DPDK application, I do some binding and rebinding of drivers. If something fails in init (e.g. no hugepages available for reservation) then my devices are left in a bad state without the proper drivers set.

I'll add exact cases where this occurs for me shortly. I want to retest to make sure of their root cause.

**Comment by ifilippov** [comment]
Hi @blitzrk I haven't found Fatal errors in SystemInit - they can be inside DPDK initialization, but I need reproducer for this to report to them.

SystemStart has couple Fatal errors as a result for setAffinity problem. Plus some flow functions like read/write have additional Fatals. All these functions run after initialization stage - it is unclear what to do in this case. Do you propose to stop everything and return from SystemStart with some error? Could you please provide some reproducer for this?

**Comment by ifilippov** [comment]
Close this for now, feel free to reopen if it is still an issue.
