### ISSUE TITLE
Cleanup KNIs

### ISSUE THREAD

**Issue by blitzrk** [intel-go/nff-go#505]
I believe either `nff_go_stop` or `flow.StopPort` be calling `rte_kni_release` on each of the `rte_kni*` in `low.h`’s `kni[MAX_KNI]` array.

**Comment by ifilippov** [comment]
Fix by https://github.com/intel-go/nff-go/pull/510, can you please check, that fix is enough?

**Comment by blitzrk** [comment]
LGTM. Thanks!
