### ISSUE TITLE
Docker checksum mismatch

### ISSUE THREAD

**Issue by shemminger** [intel-go/nff-go#525]
Build is failing for me. It is an issue with the docker package checksum.
$ go get github.com/docker/docker@v1.13.1
go: downloading github.com/docker/docker v1.13.1
go: verifying github.com/docker/docker@v1.13.1: checksum mismatch
	downloaded: h1:IkZjBSIc8hBjLpqeAbeE5mca5mNgeatLHBy3GO78BWo=
	go.sum:     h1:5VBhsO6ckUxB0A8CE5LlUJdXzik9cbEbBTQ/ggeml7M=

**Comment by gshimansky** [comment]
Unfortunately I fail to reproduce this. What happens when you run `go mod download`? Can you remove everything in your `$GOPATH/pkg/mod/github.com/docker/docker@v1.13.1` and try again?

**Comment by gshimansky** [comment]
I found a Go bug report that versions before 1.11.4 computed checksums incorrectly https://github.com/golang/go/issues/29278. We will fix this because our docker checksum was computed with version 1.11.2. Cleaning `$GOPATH/pkg/mod/cache` is required when switching versions.

**Comment by shemminger** [comment]
On Tue, 08 Jan 2019 11:40:45 -0800
Gregory Shimansky <notifications@github.com> wrote:

> I found a Go bug report that versions before 1.11.4 computed checksums incorrectly https://github.com/golang/go/issues/29278. We will fix this because our docker checksum was computed with version 1.11.2. Cleaning `$GOPATH/pkg/mod/cache` is required when switching versions.
> 


Thanks, for finding this. I was busy switching over to trying on Ubuntu LTS on Azure this morning.

**Comment by gshimansky** [comment]
A hotfix PR #530 has been integrated into master and new release v0.7.2 issued to address this problem. New requirement for lowest Go version now is 1.11.4.
