### ISSUE TITLE
pktgen-dpdk build fails with Debian testing

### ISSUE THREAD

**Issue by shemminger** [intel-go/nff-go#526]
Already fixed upstream, submodule is outdated.

**Comment by aregm** [comment]
@gshimansky Please update submodule.

**Comment by aregm** [comment]
@shemminger As we removed DPDK pktgen dependency, and switched to NFF-Go powered traffic generator - do you still need this? Or we can point to the download place. We would like to keep backward compatibility in a rational range.

**Comment by gshimansky** [comment]
I updated pktgen version to 3.6.5. Reopen this bug if it didn't help.
