### ISSUE TITLE
Run nff-go on Azure

### ISSUE THREAD

**Issue by guesslin** [intel-go/nff-go#561]
Hi, I'm trying to run nff-go on Azure VM

I'm using Ubuntu 16.04 with kernel 4.15.0-1037-azure, DPDK 18.11, and nff-go v0.7.3.
We still hit `Requested receive port exceeds number of ports which canbe used by DPDK (bind to DPDK). (3)` problem.

Any advice and suggestions will be greatly appreciated.

- dpdk-devbind
```
$ ./dpdk-devbind.py --status

Network devices using kernel driver
===================================
910e:00:02.0 'MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function] 1004' if=enP37134p0s2 drv=mlx4_core unused=

No 'Crypto' devices detected
============================

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================
```

- ifconfig
```
enP37134p0s2 Link encap:Ethernet  HWaddr 00:0d:3a:12:eb:f6
          UP BROADCAST RUNNING SLAVE MULTICAST  MTU:1500  Metric:1
          RX packets:32 errors:0 dropped:0 overruns:0 frame:0
          TX packets:74 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2146 (2.1 KB)  TX bytes:6042 (6.0 KB)

eth0      Link encap:Ethernet  HWaddr 00:0d:3a:1d:66:d4
          inet addr:10.240.0.102  Bcast:10.240.255.255  Mask:255.255.0.0
          inet6 addr: fe80::20d:3aff:fe1d:66d4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2402331 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1106371 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2773705355 (2.7 GB)  TX bytes:227647628 (227.6 MB)

eth1      Link encap:Ethernet  HWaddr 00:0d:3a:12:eb:f6
          inet addr:10.240.254.104  Bcast:10.240.255.255  Mask:255.255.0.0
          inet6 addr: fe80::20d:3aff:fe12:ebf6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:67 errors:0 dropped:0 overruns:0 frame:0
          TX packets:74 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4822 (4.8 KB)  TX bytes:6018 (6.0 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:174 errors:0 dropped:0 overruns:0 frame:0
          TX packets:174 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:12548 (12.5 KB)  TX bytes:12548 (12.5 KB)
```
- ethtool -i enP37134p0s2
```
driver: mlx4_en
version: 4.0-0
firmware-version: 2.41.7004
expansion-rom-version:
bus-info: 910e:00:02.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
```

- lspci
```
0000:00:00.0 Host bridge: Intel Corporation 440BX/ZX/DX - 82443BX/ZX/DX Host bridge (AGP disabled) (rev 03)
0000:00:07.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 01)
0000:00:07.1 IDE interface: Intel Corporation 82371AB/EB/MB PIIX4 IDE (rev 01)
0000:00:07.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 02)
0000:00:08.0 VGA compatible controller: Microsoft Corporation Hyper-V virtual VGA
910e:00:02.0 Ethernet controller: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function]
```

**Comment by gshimansky** [comment]
The general rule is that you need to bind ports to DPDK driver. NFF-Go works only with ports bound to DPDK because it addresses them with indexes which start from zero. If there are no ports bound to DPDK, then even port with index 0 is not available, and you get that error message.

There are two possible ways to bind network interface to DPDK driver.

New way uses `Netvsc` (module `uio_hv_generic`) and here is the manual https://doc.dpdk.org/guides/nics/netvsc.html . You will need to switch to kernel 4.18 or newer for this. According to @shemminger this new driver is not yet free of bugs and doesn't handle application restart. Maybe in newer versions it will behave better.

Old way with failsafe driver with instructions here https://doc.dpdk.org/guides/nics/fail_safe.html and here https://docs.microsoft.com/en-us/azure/virtual-network/setup-dpdk . Also read my and @shemminger notes about using it on Azure here https://github.com/intel-go/nff-go/issues/467#issuecomment-453620921 .

**Comment by shemminger** [comment]
On Thu, 21 Feb 2019 07:12:27 -0800
Gregory Shimansky <notifications@github.com> wrote:

> The general rule is that you need to bind ports to DPDK driver. NFF-Go works only with ports bound to DPDK because it addresses them with indexes which start from zero. If there are no ports bound to DPDK, then even port with index 0 is not available, and you get that error message.
> 
> There are two possible ways to bind network interface to DPDK driver.
> 
> New way uses `Netvsc` (module `uio_hv_generic`) and here is the manual https://doc.dpdk.org/guides/nics/netvsc.html . You will need to switch to kernel 4.18 or newer for this. According to @shemminger this new driver is not yet free of bugs and doesn't handle application restart. Maybe in newer versions it will behave better.

Recommended kernel for netvsc_pmd is 4.20.6 or later.  The fixes will also be backported to 4.19 (LTS) but not sure about what
version yet.


> Old way with failsafe driver with instructions here https://doc.dpdk.org/guides/nics/fail_safe.html and here https://docs.microsoft.com/en-us/azure/virtual-network/setup-dpdk . Also read my and @shemminger notes about using it on Azure here https://github.com/intel-go/nff-go/issues/467#issuecomment-453620921 .
>

**Comment by gshimansky** [comment]
Did last comments help? I am thinking of closing this issue if there are no other questions within several days.

**Comment by guesslin** [comment]
@gshimansky yes, we're going to upgrading the nff-go version and the kernel version.

**Comment by gshimansky** [comment]
Ok then, closing this issue

**Comment by darinkes** [comment]
Hey, @gshimansky can you write the commands down that need to be entered on an Ubuntu 18.04 VM in Azure to use nff-go? I'm having a hard time figuring out from the docs, what needs to be done.
