### ISSUE TITLE
DPDK binds to all the available interfaces and it will interrupt connectivity

### ISSUE THREAD

**Issue by ader1990** [intel-go/nff-go#562]
How do I whitelist dpdk devices before I run make perf_testing? For the moment, nff-go uses dpdk in a way that it will bind also the management interface and I lose connectivity to the machine.

Note: I try to run NFF-GO on Azure.

**Comment by gshimansky** [comment]
Can you please describe what is happening? What command do you use that binds all ports to DPDK? I think all our test programs use ports already bound and it is user responsibility to do this before running NFF-Go program.

**Comment by ader1990** [comment]
On Azure, there is no command to bind the ports to DPDK. DPDK considers that all interfaces are usable. Is there an option for nff-go to specify a PCI id whitelist? or something similar?

**Comment by gshimansky** [comment]
AFAIK you still need to bind ports on Azure. I answered a question about binding ports in another issue here https://github.com/intel-go/nff-go/issues/561#issuecomment-466036112 .

When I use a 2nd way to bind ports (https://github.com/intel-go/nff-go/issues/467#issuecomment-453620921) to `failsafe` driver I indeed had add `-w` switch to `testpmd` or it binds all of network ports available on the system. When `-w` switch is specified, it pays attention to other switches that I specified, and binds only cards that I listed on command line.

**Comment by ader1990** [comment]
I know that DPDK should automatically bind all the nics that do not have routes, but this does not happen for some reason when using NFF-GO and I lose connectivity to the management one.

**Comment by gshimansky** [comment]
What command do you use to bind ports to DPDK?

**Comment by ader1990** [comment]
> What command do you use to bind ports to DPDK?

there is no command to bind, they are automatically bound when DPDK process starts.

**Comment by gshimansky** [comment]
What kind of system are you running on Azure? I use Ubuntu Server 18.04 LTS with kernel 4.18. I have one physical PCI NIC
```
lspci | grep Ether
8304:00:02.0 Ethernet controller: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function]
```
and three NICs overall:
```
ip addr show up
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:3b:2a:44 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.7/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:fe3b:2a44/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:31:b5:38 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.5/24 brd 10.0.0.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:fe31:b538/64 scope link
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:38:09:da brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.6/24 brd 10.0.0.255 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:fe38:9da/64 scope link
       valid_lft forever preferred_lft forever
5: rename5: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master eth0 state UP group default qlen 1000
    link/ether 00:0d:3a:3b:2a:44 brd ff:ff:ff:ff:ff:ff
```
My SSH connection comes to `eth0` NIC because that is what Azure external IP is connected to:
```
sudo netstat -tapwn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      8423/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1526/sshd
tcp        0    232 10.0.0.7:22             192.55.54.39:64748      ESTABLISHED 14631/sshd: gashima
tcp6       0      0 :::22                   :::*                    LISTEN      1526/sshd
raw6       0      0 :::58                   :::*                    7           8400/systemd-networ
raw6       0      0 :::58                   :::*                    7           8400/systemd-networ
raw6       0      0 :::58                   :::*                    7           8400/systemd-networ
```

This is because all additional NICs are pseudo devices that don't have a PCI id in the system. They have to be bound using `testpmd` command using either of the two ways that I gave links to above. If no ports are bound and I try to run any nff-go example, I get an error `ERROR: failed with message and code: Requested send port exceeds number of ports which can be used by DPDK (bind to DPDK). (3)` because no ports are bound to DPDK.

Can you share output of the following commands `lspci | grep Ethernet`, `ip addr show`, `sudo netstat -tapwn`, `lsb_release -a` and `uname -a` ?

**Comment by ader1990** [comment]
@gshimansky for me this happens because I have only 3 nics, all 3 are accelerated nics (appear in lspci), so DPDK binds them all when is started by NFF-GO.

I guess I have to create a VM with the first nic being a normal one, and the other two accelerated -- this way will work, but it was not my initial question, I am not looking for a workaround.

My question is how can I tell NFF-GO to not bind/use all my NICS to/for the DPDK drivers?

**Comment by ader1990** [comment]
@gshimansky, here are the outputs, as requested:

```
lspci | grep Ethernet
0001:00:02.0 Ethernet controller: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function]
0002:00:02.0 Ethernet controller: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function]
0003:00:02.0 Ethernet controller: Mellanox Technologies MT27500/MT27520 Family [ConnectX-3/ConnectX-3 Pro Virtual Function]
```

```
ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:fd:55:b2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.4/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:fefd:55b2/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:fd:5a:25 brd ff:ff:ff:ff:ff:ff
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:fd:5c:24 brd ff:ff:ff:ff:ff:ff
5: rename5: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master eth0 state UP group default qlen 1000
    link/ether 00:0d:3a:fd:55:b2 brd ff:ff:ff:ff:ff:ff
6: rename6: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master eth1 state UP group default qlen 1000
    link/ether 00:0d:3a:fd:5a:25 brd ff:ff:ff:ff:ff:ff
7: rename7: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master eth2 state UP group default qlen 1000
    link/ether 00:0d:3a:fd:5c:24 brd ff:ff:ff:ff:ff:ff
```

```
sudo netstat -tapwn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      918/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1211/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1211/sshd
raw6       0      0 :::58                   :::*                    7           917/systemd-network

```

```
kernel and OS: 4.18.0-1011-azure Ubuntu 18.04.2 LTS

**Comment by gshimansky** [comment]
Ok I see now the difference between our configurations. I didn't find how to add a "real" accelerated NIC in Azure, and therefore all NICs that it added for mere are pseudo and unaccelerated. This doesn't answer a question of why you are getting your NICs bound to DPDK automatically because it shouldn't happen and never happened in my experience.

What NFF-Go programs are you trying to run and what is their output before you lose management connection? Can you try to add this to NFF-Go initialization to see more output?
```
        nffgoconfig := flow.Config{
                DPDKArgs:         []string{"--log-level=8"},
        }
```
What happens if you run `testpmd` application from DPDK? Can you run it like this `sudo ./testpmd -c 0x3 -- -i` and show its output to command `show port info all`?

I also don't see your SSH connection in your `sudo netstat -tapwn` output. There are only `LISTEN` socket states and no `ESTABLISHED`. What is the way are you getting to your systems in Azure?

**Comment by gshimansky** [comment]
Did my last comment help? I am thinking of closing this issue if there are no other questions within several days.
