### ISSUE TITLE
ParseData and GetPacketPayload should deal with ARPs

### ISSUE THREAD

**Issue by ifilippov** [intel-go/nff-go#584]

**Comment by gshimansky** [comment]
I don't quite understand how these two functions are related to ARP. Could you please explain?

**Comment by ifilippov** [comment]
They support ICMP, I suppose that they should support ARP as well (maybe return nil or so)

**Comment by gshimansky** [comment]
ICMP and other IP protocols consist of header+payload. For ARP there is no payload, ARP header is the sole contents of an ARP packet.
