### ISSUE TITLE
103 line of MPLS - wrong comment

### ISSUE THREAD

**Issue by ifilippov** [intel-go/nff-go#588]

**Comment by dhenza** [comment]
Pull request #635 submitted to address this.

**Comment by gshimansky** [comment]
It would be more appropriate to merge all pull requests into `devel` branch because `master` serves as a clean snapshot of latest released version.

**Comment by dhenza** [comment]
Makes sense, shall I revert the change and submit new pull request to devel?

**Comment by aregm** [comment]
@dhenza yes, please.
