### ISSUE TITLE
libnl.h?

### ISSUE THREAD

**Issue by FOXNEOAdvancedTechnology** [intel-go/nff-go#594]
Where can I get libnl/libnl.h for RHEL?  I "yum install libnl3" but there is no /usr/include/libnl installed.  Make keeps failing

`/home/ec2-user/nff-go/dpdk/dpdk/drivers/net/mlx5/mlx5_flow_tcf.c:8:27: fatal error: libmnl/libmnl.h: No such file or directory"`

**Comment by aregm** [comment]
@FOXNEOAdvancedTechnology have you tried `yum install libmnl-devel` too? This should install head to `/usr/include/libmnl/libmnl.h`.

**Comment by FOXNEOAdvancedTechnology** [comment]
Not in RHEL, all they have is the non-devel:
```
# yum list available  | grep mnl
libmnl.i686                   1.0.3-7.el7       rhui-REGION-rhel-server-releases
```
I found the source code for libmnl here:
https://www.netfilter.org/projects/libmnl/downloads.html
