### ISSUE TITLE
Failed to upgrading nff-go to v0.8.0 caused by mlx drivers

### ISSUE THREAD

**Issue by mkfsn** [intel-go/nff-go#597]
Hi, I'm trying to upgrade nff-go from v0.7.0 to v0.8.0 but getting some dependency problems.

I saw there's a commit that nff-go needs `libmnl-dev` and `libibverbs-dev`: https://github.com/intel-go/nff-go/commit/2b5952aab0a75c2096ac354fa9deb16c8b5150ee

I'm using Debian stretch, and I've installed those two packages. However, it seems like the default `libibverbs-dev` on Debian stretch is version 1.2.1-2 and thus doesn't contain:

- infiniband/mlx4dv.h

which leads to the following error:

```
fatal error: infiniband/mlx4dv.h: No such file or directory
```

Then I also tried to install a later version, e.g. 16.0 from the backport:
https://packages.debian.org/stretch-backports/amd64/libibverbs-dev/download

It seems to work fine, but then I'm getting the following error while `make dpdk`:

```
/usr/bin/ld: cannot find -lmlx4
/usr/bin/ld: cannot find -lmlx5
```

Did I do something wrong?

Also, can you provide a system requirement version list? For example, the version of libiverbs - I'm pretty sure libibverbs-dev 1.2.1 doesn't work but I don't know what is the minimum support version.

**Comment by gshimansky** [comment]
[DPDK documentation on MLX driver](https://doc.dpdk.org/guides/nics/mlx5.html) doesn't provide library versions, it only mentions that you need the following libraries to be installed `libibverbs`, `libmlx5` and `libmnl`. If you installed all of them and still fail to build, you can try to disable MLX altogether by commending line `sed -ri 's,(MLX._PMD=)n,\1y,' $(DPDK_DIR)/build/.config` in `dpdk/Makefile`.
I need to think of a better way to disable building this driver if build problems are too hard to overcome on old Linux installations.

**Comment by mkfsn** [comment]
@gshimansky Thanks for your help!
After disabling the MLX stuff it's now working fine! Thanks a lot!
