### ISSUE TITLE
Getting started on developing with nff-go

### ISSUE THREAD

**Issue by ntcong** [intel-go/nff-go#632]
I'm trying to start developing a new project with nff-go, currently the doc is a little confusing with how to start running a new project. Most examples have Makefile with some dependent mk file.
What I did:
```
mkdir -p ~/go/src/github.com/intel-go/
git clone --recurse-submodules http://github.com/intel-go/nff-go
cd nff-go
make -j10
```
The building was successful, but when I make a new file with just this
```
package main

import "github.com/intel-go/nff-go/flow"

func main() {
        flow.SystemInit(nil)
        flow.SystemStart()
}
```
```
go build
go build github.com/intel-go/nff-go/internal/low: invalid flag in #cgo LDFLAGS: -Wl,--whole-archive
```

Can someone point me to the right direction?

**Comment by ntcong** [comment]
Seems that I need to source a bunch of environment like in mk/include.mk file

**Comment by gshimansky** [comment]
You can use project https://github.com/intel-go/nff-go-nat as an illustration on how to create a separate application which uses nff-go as a dependency. In general, you need some script (shell or Makefile) to set up several environment variables correctly before calling `go build` command.
