### ISSUE TITLE
run tutorial can't bindports

### ISSUE THREAD

**Issue by riggy2013** [intel-go/nff-go#659]
I installed vagrant per tutorial guide. However, after successful installation, the first step failed.
 
$ vagrant ssh nff-go-1 
nff-go-1$ bindports
 
When I bindports, it reports:
 
$ bindports
insmod: ERROR: could not load module /home/vagrant/nff-go/dpdk/dpdk/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko: No such file or directory
Warning: no supported DPDK kernel modules are loaded
Error: Driver 'igb_uio' is not loaded.
 
The scripts for bindports is as below:
 
bindports ()
{
    sudo modprobe uio
    sudo insmod "$NFF_GO"/dpdk/dpdk/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
#    sudo insmod "$NFF_GO"/dpdk/dpdk/x86_64-native-linuxapp-gcc-install/lib/modules/5.0.0-31-generic/extra/dpdk/igb_uio.ko
    sudo "$NFF_GO"/dpdk/dpdk/usertools/dpdk-devbind.py --bind=igb_uio $NFF_GO_CARDS
}
 
But there is no directory of x86_64-native-linuxapp-gcc/kmod/igb_uio.ko. I changed to the existed directory as x86_64-native-linuxapp-gcc-install/lib, it then reports:
 
$ bindports
Unknown device: 00:06.0. Please specify device in "bus:slot.func" format
 
Here is my lspci output:
 
$ lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371AB/EB/MB PIIX4 IDE (rev 01)
00:02.0 VGA compatible controller: InnoTek Systemberatung GmbH VirtualBox Graphics Adapter
00:03.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
00:04.0 System peripheral: InnoTek Systemberatung GmbH VirtualBox Guest Service
00:07.0 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 08)
00:08.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
00:09.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
 
any idea?

BTW, is here the right place to ask such support question? or any other community?

Thanks in advance!

**Comment by gshimansky** [comment]
You are right, `bindports` got outdated and the path is wrong. I fixed it in PR #660. If your NICs PCI IDs are different from those specified in the script you can edit it and change them.

Meanwhile you can try to use my scripts that I use for automated testing. They are much more powerful than those set up in VMs by default and allow switching from DPDK configuration to Linux and some Linux networking configuration https://github.com/gshimansky/network-setup-scripts

**Comment by gshimansky** [comment]
Path to module fixed in `devel` branch.

**Comment by riggy2013** [comment]
Greg,

My system is running successfully now with your scripts. Thanks a lot.

I'll try your new checkin later.
