### ISSUE TITLE
How to get packet arriving timestamp?

### ISSUE THREAD

**Issue by cang233** [intel-go/nff-go#685]
I set the 
```
	config := flow.Config{
		CPUList:              "0-3",
		HWRXPacketsTimestamp: true,
	}
```
and use packet.GetPacketTimestamp() to get timestamp but return 0.

why?

**Comment by gshimansky** [comment]
This flag only enables capability of a NIC, it has to be supported by hardware to work correctly. AFAIK at the moment only Mellanox NICs support this feature, I implemented this flag for those cards. You can use `flow.CheckHWCapability(flow.HWRXPacketsTimestamp)` to query whether a network card supports this feature.

**Comment by cang233** [comment]
oh,I get it,thanks a lot!
