### ISSUE TITLE
nff-go examples on Kubernetes

### ISSUE THREAD

**Issue by ivanayov** [intel-go/nff-go#702]
Hello, 

Are there any docs/tutorials for running and testing the nff-go examples on Kubernetes?
I can build the images and do my own deployments, but I wanted to check if there is something already done by the community in that direction, as I couldn't find in the documentation/blog posts/etc.

Thanks,
Ivana

**Comment by sitilge** [comment]
Hi,

You can check the related project here: https://github.com/intel-go/nff-go-nat

**Comment by ivanayov** [comment]
Thank you @sitilge 

I build `nff-go-base` image as required, but when I try to build nff-go-nat it tries to copy `nff-go-nat` from `nff-go-base` and fails.
Feels like something's wrong - the project trying to copy itself from a dependency. Am I missing something?

Or if it's a bug I'll open an issue there.

Thanks

**Comment by aregm** [comment]
@ivanayov by `nff-go-base` you mean nff-go repo? Can you send the reproducing steps?

**Comment by ivanayov** [comment]
@aregm yes, those are the steps:
1. Go to `nff-go/nff-go-base`
2. Run `make Dockerfile`
3. Run `docker build --build-arg USER_NAME=<my_user_name>`
4. In `nff-go-nat` run `docker build --build-arg USER_NAME=<my_user_name> .`
5. Fails on `COPY nff-go-nat .`

I first tried with `nff-go`, then I saw I need only `nff-go-base`.

**Comment by gshimansky** [comment]
`COPY nff-go-nat .` fails because you have not built `nff-go-nat` executable in the current directory. You are interpreting `Makefile` targets manually but you didn't notice that `images` target depends on `all` which should build `nff-go-nat` before building an image.

**Comment by aregm** [comment]
@ivanayov - Ivana can I close this issue?

**Comment by ivanayov** [comment]
Yes, I'm going to close it. Thanks.
