### ISSUE TITLE
Perfoormance Comparison

### ISSUE THREAD

**Issue by drobinkent** [intel-go/nff-go#708]
Assume we have 2 implementation of a NF. How to compare their performance in terms of packet processing throughput? Is there any facility in the framework to do this kind of comparison?

**Comment by aregm** [comment]
@drobinkent You can get the stats from NFF-Go application using the standard framework capabilities, e.g. look into tests/performance/latency.go or to an example https://github.com/intel-go/nff-go/tree/master/examples/antiddos. This you can collect the needed statistics. Then you can compare with the 2nd implementation, which I assume is not written in NFF-Go. Or did you mean that you have 2 versions both written in NFF-Go?

**Comment by drobinkent** [comment]
Both written in NFF-GO

**Comment by aregm** [comment]
We do not have a standardized framework for performance comparison. You can use the https://github.com/intel-go/nff-go/blob/master/test/performance/perf_count.go as a reference. Feel free to contribute such a framework to be used in NFF-Go.

**Comment by drobinkent** [comment]
thanks
